### ISSUE TITLE
DieHard code from Video4 slides has a bug

### ISSUE THREAD

**Issue by stchang** [tlaplus/www#2]
Is there a mistake in the `BigToSmall` line of [the Video4 script, slide 302](http://lamport.azurewebsites.net/video/video4-script.pdf)?

It should be `/\ big' = big - (3 - small)`?

**Comment by muenchnerkindl** [comment]
I agree, thanks for catching this.

**Comment by stchang** [comment]
fwiw the same typo also appears in the video and the zip html.

**Comment by xxyzzn** [comment]
This error has been added to the [corrections file](http://lamport.azurewebsites.net/video/corrections.html).
